### ISSUE TITLE
我本地没法跑

### ISSUE THREAD

**Issue by monolithic** [piggsoft/beetl-spring-boot#2]
我参照着example写，但是访问 localhot:8080永远是whitelabel Error Page
最终发现是包路径的问题，example项目必须要是com.piggsoft才可以
重现方法：修改beetl-spring-boot-example，包路径修改为其他就没法正常打开页面了

**Comment by piggsoft** [comment]
我又在试了下，不会出现这种情况，你的Controller是怎么写的

**Comment by piggsoft** [comment]
一般会在404时出现这个页面，也就是你的Controller的配置有问题。

**Comment by piggsoft** [comment]
这个issue我关了哈，有什么问题再联系我
